[package]
name = "winit_test"
version = "0.1.0"
edition = "2021"

[dependencies]
# Open a window
winit = "0.29"
# To view WGPU's env_logger output
env_logger = "0.11"

wgpu = "0.19"
pollster = "0.3.0"
